### PR TITLE
gradle build file

### PR DESCRIPTION
**Pull request by bkonev**
Testing how github works :)

it seems that gradle build files are easy and handle the dependencies.

However, currently there is a problem is that axiom comparison is based on the name of the defined concept and so in case of RCI the ordering is undefined. While the cyclicity test passes in idea, it does not work in gradle.

### CODE REVIEW

**Comment by bkonev** [comment]
developing MEX

**Comment by bkonev** [comment]
it runs. However, on my examples so far, mex-star == star

**Comment by bkonev** [comment]
Hi William,

Sent from my iPhone

On 30 May 2017, at 18:29, William Gatens <notifications@github.com<mailto:notifications@github.com>> wrote:


Not used gradle before but I did start on a maven branch (which you can see in the branches tab) which does the same job should have mentioned this before, doesn't really matter which we use though.

I haven't used either till now, but I've found gradle easier to configure. I'm not sure if all my pull requests got through but if y clone my fork simply say
  # gradle run
And it'll run module extraction.


I'm leaving for holiday tomorrow but will take a look at the code when I get back if it can wait but looks like you've done the right thing w.r.t the implement of the hybrid extractor.

I thought you were already gone:). Please pay no attention to my past (and future emails) until you have time.



What would be nice is a worked example or two that we can put in the test directory where hybrid MEX-STAR is smaller than STAR.

True. I'll have a look at your examples where Amex hybrid works well.

Boris

-

**Comment by bkonev** [comment]
turned out that galen is a good example. 

Boris
> On 30 May 2017, at 18:29, William Gatens <notifications@github.com> wrote:
> 
> You seem to have the hang of how things are working and have worked out the comparator problem with the test. Not used gradle before but I did start on a maven branch (which you can see in the branches tab) which does the same job should have mentioned this before, doesn't really matter which we use though.
> 
> I'm leaving for holiday tomorrow but will take a look at the code when I get back if it can wait but looks like you've done the right thing w.r.t the implement of the hybrid extractor. What would be nice is a worked example or two that we can put in the test directory where hybrid MEX-STAR is smaller than STAR.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Prof. Boris Konev
University of Liverpool
Department of Computer Science
Liverpool, L69 3BX, UK
Email: konev@csc.liv.ac.uk
Tel: (+44) 151 795 4260
URL: http://www.csc.liv.ac.uk/~konev

**Comment by sadger** [comment]
Sounds promising, what kind of signatures and what's the module size difference? Be nice to have such an important ontology showing promising things.

**Comment by sadger** [comment]
Had a look at axiom signatures on galen too and looks promising. Tambis from TONES seems interesting mostly MEX-STAR is often the same as STAR and sometimes smaller but AMEX-STAR is smaller still in some cases. The people ontology is another example of this.  The worm phenotype ontology seems to have small modules but both AMEX-STAR and MEX-STAR are often smaller than STAR on it's own. I think I have my repository of ontologies I used for my thesis evaluation which is a mixture of tones and bioportal with largely EL stripped out and axioms removed from ontologies until they are SHIQ at most (due to the limitations of the n-depleting modules w.r.t nominals). I can send you this if it's of use.

**Comment by bkonev** [comment]
Hi William,

sorry for tardiness. Yes it would be great if you could share these ontologies. 

One question we face is whether we can reuse the stats that you’ve already collected for the thesis or we need to rerun (at least some of) the experiments. Would you remember on the top of your head how long the 1-inseparabilty experiments took overall? for 1-2-etc inseparable we certainly do not need to rerun anything as this is about comparing different forms of approximation. 

Could you have  a look at the mex hybrid code, please? I hope I haven’t messed it up too much.

Boris


> On 10 Jun 2017, at 14:16, William Gatens <notifications@github.com> wrote:
> 
> Had a look at axiom signatures on galen too and looks promising. Tambis from TONES seems interesting mostly MEX-STAR is often the same as STAR and sometimes smaller but AMEX-STAR is smaller still in some cases. The people ontology is another example of this. The worm phenotype ontology seems to have small modules but both AMEX-STAR and MEX-STAR are often smaller than STAR on it's own. I think I have my repository of ontologies I used for my thesis evaluation which is a mixture of tones and bioportal with largely EL stripped out and axioms removed from ontologies until they are SHIQ at most (due to the limitations of the n-depleting modules w.r.t nominals). I can send you this if it's of use.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Prof. Boris Konev
University of Liverpool
Department of Computer Science
Liverpool, L69 3BX, UK
Email: konev@csc.liv.ac.uk
Tel: (+44) 151 795 4260
URL: http://www.csc.liv.ac.uk/~konev

**Comment by sadger** [comment]
I've just realised why the STAR module can seem smaller than the MEX-STAR hybrid it'll be the size of the final STAR-AMEX module rather than first extraction. Rather than copying the star module into it's own variable it's just pointing to the final module so more stuff is getting removed. Will fix this.

**Pull request closed without merging**
